StockCrawler:
  # debug 여부 - log level 결정
  debug: True
  save_file_path: ./Output
  # Database information for data save or read.
  DB_ip: 192.168.0.12
  DB_port: 27017
  DB_name: Changsung
  save_collection_name: stock_test
  # Get target company names
  # DB or File
  company_name_location: DB
  target_collection_name: stock_category
  target_file_path: ./
  target_file_name: test.csv
  # Periodically set for execution.
  iterate: True
  # Set the range of the publish date of news data to be fetched date.
  start_date: 2020.06.01
  end_date: 2020.06.15
